channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.5.0
  - scipy==1.16.0
name: mlflow-env
