name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install build tools
        run: |
          choco install visualcpp-build-tools -y
          choco install ninja -y
          refreshenv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Lint code with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203

      - name: Run tests with pytest
        run: |
          pytest tests/ --doctest-modules --junitxml=test-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: Build and run notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/2.0-eda-task2.ipynb --output notebooks/2.0-eda-task2-output.ipynb

      - name: Deploy (example placeholder)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Deploying to staging environment..."
          # Add deployment commands here (e.g., Docker build and push)