name: Minimal CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Lint code with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203

      - name: Build and run notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/2.0-eda-task2.ipynb --output notebooks/2.0-eda-task2-output.ipynb

      - name: Upload notebook output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notebook-output
          path: notebooks/2.0-eda-task2-output.ipynb