name: CI/CD Pipeline for Credit Risk Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: false

    - name: Lint code
      run: |
        pip install flake8
        flake8 src/ tests/ --max-line-length=120 --ignore=E203,W503
      continue-on-error: false

    - name: Run tests
      run: |
        pytest tests/ -v --maxfail=1
      continue-on-error: false